server:
  port: 8097

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8082
        auto.register.schemas: true

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: transaction-service-group
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://localhost:8082
        specific.avro.reader: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/bd-transaction

# Timeout para validación de cuenta
transaction:
  validation:
    timeout-seconds: 10