server:
  port: 8099

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true

    consumer:
      group-id: transaction-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/bd-transaction

# Timeout para validación de cuenta
transaction:
  validation:
    timeout-seconds: 10

logging:
  level:
    root: INFO
    com.nttdata.transaction_service: DEBUG